name: montessori-retrieval
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - sentence-transformers
      - rank-bm25
      - bertopic
      - umap-learn
      - hdbscan
      - streamlit
      - nltk
      - tqdm